[package]
name = "vpiper-wasm"
version = "0.1.0"
authors = ["mikbry <mik@miklabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
vpiper = { path = "../../core" }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'MediaSource',
  'MediaRecorder',
]